#!/usr/bin/env bash
set -euo pipefail

version="${1:-}"
pkgrel="${PKGREL:-1}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
binary="$repo_root/src-tauri/target/release/voxpen-desktop"
paste_helper="$repo_root/src-tauri/resources/voxpen-paste.sh"
icon="$repo_root/src-tauri/icons/128x128.png"
out_dir="$repo_root/src-tauri/target/release/bundle/arch"

if [[ -z "$version" ]]; then
  version="$(node -p "require('./package.json').version")"
fi

if [[ ! -x "$binary" ]]; then
  echo "Missing release binary: $binary" >&2
  echo "Run: pnpm tauri build --bundles deb appimage" >&2
  exit 1
fi

if ! command -v zstd >/dev/null 2>&1; then
  echo "zstd is required to create .pkg.tar.zst" >&2
  exit 1
fi

pkgver="${version}-${pkgrel}"
work_dir="$(mktemp -d)"
pkg_dir="$work_dir/pkg"
trap 'rm -rf "$work_dir"' EXIT

mkdir -p \
  "$pkg_dir/usr/bin" \
  "$pkg_dir/usr/share/applications" \
  "$pkg_dir/usr/share/icons/hicolor/128x128/apps"

install -Dm755 "$binary" "$pkg_dir/usr/bin/voxpen-desktop"
install -Dm755 "$paste_helper" "$pkg_dir/usr/bin/voxpen-paste.sh"
install -Dm644 "$icon" "$pkg_dir/usr/share/icons/hicolor/128x128/apps/voxpen-desktop.png"

cat > "$pkg_dir/usr/share/applications/voxpen-desktop.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=VoxPen Desktop
Comment=System-tray voice dictation for every desktop app
Exec=voxpen-desktop
Icon=voxpen-desktop
Terminal=false
Categories=Utility;AudioVideo;Audio;
StartupNotify=false
EOF

installed_size="$(du -sb "$pkg_dir" | awk '{print $1}')"
build_date="$(date +%s)"

cat > "$pkg_dir/.PKGINFO" <<EOF
# Generated by scripts/package-arch.sh
pkgname = voxpen-desktop
pkgbase = voxpen-desktop
pkgver = $pkgver
pkgdesc = System-tray voice dictation for every desktop app
url = https://github.com/soanseng/voxpen-desktop
builddate = $build_date
packager = VoxPen CI
size = $installed_size
arch = x86_64
license = custom
depend = gtk3
depend = webkit2gtk-4.1
depend = libappindicator-gtk3
depend = alsa-lib
depend = librsvg
optdepend = wl-clipboard: clipboard support on Wayland
optdepend = ydotool: paste simulation on Wayland
optdepend = wtype: text input support on Wayland
EOF

mkdir -p "$out_dir"
out_file="$out_dir/voxpen-desktop_${pkgver}_x86_64.pkg.tar.zst"
tar --format=ustar --sort=name --owner=0 --group=0 --numeric-owner -C "$pkg_dir" -cf - . \
  | zstd -T0 -19 -f -o "$out_file" >/dev/null

echo "$out_file"
